services:
  database:
    image: mariadb:11
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: symfony_serial_watchers
      MARIADB_USER: symfony_serial_watchers_user
      MARIADB_PASSWORD: symfony_serial_watchers_pwd
    volumes:
      - database_data:/var/lib/mysql
    ports:
      - "3306:3306"

volumes:
  database_data:
